bind r source-file ~/.tmux.conf \; display "Reloaded!"
# perfix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix


# MOuse usage
set -g mouse on

## Increase History
set-option -g history-limit 9000


## numbering
set -g base-index 1
setw -g pane-base-index 1

# Split
bind v split-window -hc "#{pane_current_path}"
bind h split-window -vc "#{pane_current_path}"


# swapping windows
# Swap windows with Alt + arrow keys
# Swap windows with Alt + Left/Right and Alt + Up/Down
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1



bind c new-window -c "#{pane_current_path}"



bind Space last-window


# resize

bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15

# fonts 
set -g utf8 on
set-window-option -g utf8 on


# Flotting
# Switch back to main session
bind m switch-client -t main



# Simple scratchpad
set -g @tpad-scratchpad-bind   "C-j"
## Plugins
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'Subbeh/tmux-tpad'
set -g @plugin 'tmux-plugins/tmux-sensible'  # Sensible tmux defaults
set -g @plugin 'tmux-plugins/tmux-themepack'  # Themes for tmux
set -g @plugin 'tmux-plugins/tmux-yank'  # Clipboard integration
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @theme_variation 'night'

# theme
# Set the theme
set -g @tpm_theme 'powerline'
run '~/.tmux/plugins/tpm/tpm'
